## Import Library

In [ ]:
# Importing necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns

## Load Data

### Data Understanding

In [ ]:
# Load the data from CSV file
data = pd.read_csv('train.csv')

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
data.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [ ]:
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [ ]:
data.isnull().sum().sort_values(ascending=False).head(20)

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
MasVnrType       872
FireplaceQu      690
LotFrontage      259
GarageYrBlt       81
GarageCond        81
GarageType        81
GarageFinish      81
GarageQual        81
BsmtFinType2      38
BsmtExposure      38
BsmtQual          37
BsmtCond          37
BsmtFinType1      37
MasVnrArea         8
Electrical         1
Id                 0
dtype: int64

In [ ]:
data.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1379.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,46.549315,567.240411,1057.429452,1162.626712,346.992466,5.844521,1515.463699,0.425342,0.057534,1.565068,0.382877,2.866438,1.046575,6.517808,0.613014,1978.506164,1.767123,472.980137,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,161.319273,441.866955,438.705324,386.587738,436.528436,48.623081,525.480383,0.518911,0.238753,0.550916,0.502885,0.815778,0.220338,1.625393,0.644666,24.689725,0.747315,213.804841,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,0.000000,0.000000,334.000000,0.000000,0.000000,334.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,1900.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,0.000000,223.000000,795.750000,882.000000,0.000000,0.000000,1129.500000,0.000000,0.000000,1.000000,0.000000,2.000000,1.000000,5.000000,0.000000,1961.000000,1.000000,334.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,0.000000,477.500000,991.500000,1087.000000,0.000000,0.000000,1464.000000,0.000000,0.000000,2.000000,0.000000,3.000000,1.000000,6.000000,1.000000,1980.000000,2.000000,480.000000,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,0.000000,808.000000,1298.250000,1391.250000,728.000000,0.000000,1776.750000,1.000000,0.000000,2.000000,1.000000,3.000000,1.000000,7.000000,1.000000,2002.000000,2.000000,576.000000,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,1474.000000,2336.000000,6110.000000,4692.000000,2065.000000,572.000000,5642.000000,3.000000,2.000000,3.000000,2.000000,8.000000,3.000000,14.000000,3.000000,2010.000000,4.000000,1418.000000,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [ ]:
# median saleprice by lotshape

median_saleprice_by_lotshape = data.groupby('LotShape')['SalePrice'].median()
print(median_saleprice_by_lotshape)

LotShape
IR1    189000.0
IR2    221000.0
IR3    203570.0
Reg    146000.0
Name: SalePrice, dtype: float64

In [ ]:
# median saleprice by contour
median_saleprice_by_contour = data.groupby('LandContour')['SalePrice'].median()
print(median_saleprice_by_lotshape)

LotShape
IR1    189000.0
IR2    221000.0
IR3    203570.0
Reg    146000.0
Name: SalePrice, dtype: float64

In [ ]:
# median lotarea by contour
median_lotarea_by_contour = data.groupby('LandContour')['LotArea'].median()
print(median_saleprice_by_lotshape)

LotShape
IR1    189000.0
IR2    221000.0
IR3    203570.0
Reg    146000.0
Name: SalePrice, dtype: float64

In [ ]:
#median saleprice per feet square
median_saleprice_by_contour/median_lotarea_by_contour

LandContour
Bnk    16.454202
HLS    20.024327
Low    11.745070
Lvl    17.329787
dtype: float64

##Preprocessing Data

In [ ]:
# building age
data['building_age'] = data['YrSold'] - data['YearBuilt']

In [ ]:
# RemodelAge
data['RemodelAge'] = data['YrSold'] - data['YearRemodAdd']

# TotalBath: BsmtFullBath + BsmtHalfBath + FullBath + HalfBath.
data['TotalBath'] = data['BsmtFullBath'] + data['BsmtHalfBath'] + data['FullBath'] + data['HalfBath']

# TotalPorch: WoodDeckSF + OpenPorchSF + EnclosedPorch + 3SsnPorch + ScreenPorch.
data['TotalPorch'] = data['WoodDeckSF'] + data['OpenPorchSF'] + data['EnclosedPorch'] + data['3SsnPorch'] + data['ScreenPorch']

In [ ]:
# TotalBsmtSFToGrLivAreaRatio: Ratio between TotalBsmtSF (total basement area) and GrLivArea.
data['TotalBsmtSFToGrLivAreaRatio'] = data['TotalBsmtSF'] / data['GrLivArea']

# GarageAreaToLotAreaRatio: Ratio between GarageArea and LotArea
data['GarageAreaToLotAreaRatio'] = data['GarageArea'] / data['LotArea']

In [ ]:
# OverallQual_x_GrLivArea: Interaction between OverallQual and GrLivArea to measure the effect of whole quality and green living area
data['OverallQual_x_GrLivArea'] = data['OverallQual'] * data['GrLivArea']

In [ ]:
data['building_age'].describe()

count    1460.000000
mean       36.547945
std        30.250152
min         0.000000
25%         8.000000
50%        35.000000
75%        54.000000
max       136.000000
Name: building_age, dtype: float64

In [ ]:
#reclassified building category
data['building_age_category'] = np.where(data['building_age'] < 35, 'new', 'old')

In [ ]:
data['building_age_category'] = data['building_age_category'].replace({'new': 2, 'old': 1})

In [ ]:
data['MSSubClass'] = data['MSSubClass'].replace({
    20: 5,
    30: 6,
    40: 7,
    45: 8,
    50: 9,
    60: 10,
    70: 11,
    75: 14,
    80: 12,
    85: 13,
    90: 2,
    120: 4,
    150: 3,
    160: 15,
    180: 16,
    190: 1
})

In [ ]:
data['MSZoning'] = data['MSZoning'].replace({
    'A': 1,
    'C': 7,
    'C (all)': 7,
    'FV': 2,
    'I': 8,
    'RH': 6,
    'RL': 3,
    'RP': 4,
    'RM': 5
})

In [ ]:
data['LotFrontage'] = data['LotFrontage'].fillna(0)

In [ ]:
# LotFrontageToLotAreaRatio: Ration between LotFrontage and LotArea to describe proportion of lot frontage to lot area
data['LotFrontageToLotAreaRatio'] = data['LotFrontage'] / data['LotArea']

In [ ]:
data['Street'] = data['Street'].replace({'Grvl': 1, 'Pave': 2})

In [ ]:
data['Alley'] = data['Alley'].replace({'Grvl': 1, 'Pave': 2})

In [ ]:
data['Alley'].fillna(0, inplace=True)

In [ ]:
data['LotShape'] = data['LotShape'].replace({
    'Reg': 1,
    'IR1': 2,
    'IR2': 3,
    'IR3': 4
})

In [ ]:
data['LandContour'] = data['LandContour'].replace({
    'Lvl': 3,
    'Bnk': 2,
    'HLS': 4,
    'Low': 1
})

In [ ]:
data['Utilities'] = data['Utilities'].replace({
    'AllPub': 4,
    'NoSewr': 3,
    'NoSeWa': 2,
    'ELO': 1
})

In [ ]:
data['LotConfig'] = data['LotConfig'].replace({
    'Inside': 1,
    'Corner': 2,
    'CulDSac': 3,
    'FR2': 4,
    'FR3': 5
})

In [ ]:
data['LandSlope'] = data['LandSlope'].replace({
    'Sev': 1,
    'Mod': 2,
    'Gtl': 3
})

In [ ]:
data.drop(columns=['Neighborhood'], inplace=True)

In [ ]:
data = pd.get_dummies(data, columns=['Condition1','Condition2'])

In [ ]:
data['BldgType'] = data['BldgType'].replace({
    '1Fam': 5,
    'TwnhsE': 4,
    'TwnhsI': 3,
    'Twnhs' : 3,
    'Duplx': 2,
    'Duplex': 2,
    '2FmCon': 1,
    '2fmCon' : 1
})

In [ ]:
data['HouseStyle'] = data['HouseStyle'].replace({
    '1Story': 1,
    'SFoyer': 2,
    '1.5Unf': 3,
    '1.5Fin': 4,
    '2Story': 5,
    '2.5Unf': 6,
    '2.5Fin': 7,
    'SLvl': 8
})

In [ ]:
data['RoofStyle'] = data['RoofStyle'].replace({
    'Mansard': 6,
    'Gambrel': 5,
    'Hip': 4,
    'Gable': 3,
    'Shed': 2,
    'Flat': 1
})

In [ ]:
data['RoofMatl'] = data['RoofMatl'].replace({
    'ClyTile': 8,
    'WdShake': 7,
    'WdShngl': 6,
    'Metal': 5,
    'Membran': 4,
    'Tar&Grv': 3,
    'CompShg': 2,
    'Roll': 1
})

In [ ]:
data['Exterior1st'] = data['Exterior1st'].replace({
    'Stone': 17,
    'BrkFace': 16,
    'BrkComm': 15,
    'CemntBd': 14,
    'Stucco': 13,
    'WdShing': 12,
    'HdBoard': 11,
    'VinylSd': 10,
    'ImStucc': 9,
    'MetalSd': 8,
    'AsbShng': 7,
    'AsphShn': 6,
    'Plywood': 5,
    'Wd Sdng': 4,
    'CBlock': 3,
    'PreCast': 2,
    'Other': 1
})

In [ ]:
data['Exterior2nd'] = data['Exterior2nd'].replace({
    'Stone': 17,
    'BrkFace': 16,
    'BrkComm': 15,
    'Brk Cmn': 15,
    'CemntBd': 14,
    'CmentBd' : 14,
    'Stucco': 13,
    'WdShing': 12,
    'Wd Shng': 12,
    'HdBoard': 11,
    'VinylSd': 10,
    'ImStucc': 9,
    'MetalSd': 8,
    'AsbShng': 7,
    'AsphShn': 6,
    'Plywood': 5,
    'Wd Sdng': 4,
    'CBlock': 3,
    'PreCast': 2,
    'Other': 1
})

In [ ]:
data['MasVnrType'] = data['MasVnrType'].replace({
    'Stone': 5,
    'BrkFace': 4,
    'BrkCmn': 3,
    'CBlock': 1,
    'NA': 0
})

In [ ]:
data['MasVnrType'].fillna(0, inplace=True)

In [ ]:
data['MasVnrArea'].fillna(0, inplace=True)

In [ ]:
data['ExterQual'] = data['ExterQual'].replace({
    'Ex': 5,
    'Gd': 4,
    'TA': 3,
    'Fa': 2,
    'Po': 1
})

In [ ]:
data['ExterCond'] = data['ExterCond'].replace({
    'Ex': 5,
    'Gd': 4,
    'TA': 3,
    'Fa': 2,
    'Po': 1
})

In [ ]:
data['Foundation'] = data['Foundation'].replace({
    'PConc': 6,
    'Stone': 5,
    'BrkTil': 4,
    'CBlock': 3,
    'Wood': 2,
    'Slab': 1
})

In [ ]:
data['BsmtQual'] = data['BsmtQual'].replace({
    'Ex': 5,
    'Gd': 4,
    'TA': 3,
    'Fa': 2,
    'Po': 1,
    'NA': 0
})

In [ ]:
data['BsmtQual'].fillna(0, inplace=True)

In [ ]:
data['BsmtCond'] = data['BsmtCond'].replace({
    'Ex': 5,
    'Gd': 4,
    'TA': 3,
    'Fa': 2,
    'Po': 1,
    'NA': 0
})

In [ ]:
data['BsmtCond'].fillna(0, inplace=True)

In [ ]:
data['BsmtExposure'] = data['BsmtExposure'].replace({
    'Gd': 3,
    'Av': 2,
    'Mn': 1,
    'No': 0,
    'NA': 0
})

In [ ]:
data['BsmtExposure'].fillna(0, inplace=True)

In [ ]:
data['BsmtFinType1'] = data['BsmtFinType1'].replace({
    'GLQ': 6,
    'ALQ': 5,
    'BLQ': 4,
    'Rec': 3,
    'LwQ': 2,
    'Unf': 1,
    'NA': 0
})

In [ ]:
data['BsmtFinType1'].fillna(0, inplace=True)

In [ ]:
data.drop(columns=['BsmtFinSF1'], inplace=True)

In [ ]:
data['BsmtFinType2'] = data['BsmtFinType2'].replace({
    'GLQ': 6,
    'ALQ': 5,
    'BLQ': 4,
    'Rec': 3,
    'LwQ': 2,
    'Unf': 1,
    'NA': 0
})

In [ ]:
data['BsmtFinType2'].fillna(0, inplace=True)

In [ ]:
data.drop(columns=['BsmtFinSF2', 'BsmtUnfSF'], inplace=True)

In [ ]:
data['Heating'] = data['Heating'].replace({
    'GasW': 5,
    'GasA': 4,
    'OthW': 3,
    'Grav': 2,
    'Wall': 1,
    'Floor': 0
})

In [ ]:
data['HeatingQC'] = data['HeatingQC'].replace({
    'Ex': 5,
    'Gd': 4,
    'TA': 3,
    'Fa': 2,
    'Po': 1
})

In [ ]:
data['CentralAir'] = data['CentralAir'].replace({
    'Y': 2,
    'N': 1
})

In [ ]:
data['Electrical'] = data['Electrical'].replace({
    'Mix': 5,
    'SBrkr': 4,
    'FuseA': 3,
    'FuseF': 2,
    'FuseP': 1,
    'NA': 0
})

In [ ]:
data['Electrical'].fillna(0, inplace=True)

In [ ]:
data['KitchenQual'] = data['KitchenQual'].replace({
    'Ex': 5,
    'Gd': 4,
    'TA': 3,
    'Fa': 2,
    'Po': 1
})

In [ ]:
# KitchenAbvGr_x_KitchenQual:
data['KitchenAbvGr_x_KitchenQual'] = data['KitchenAbvGr'] * data['KitchenQual']

In [ ]:
data['Functional'] = data['Functional'].replace({
    'Typ': 8,
    'Min1': 7,
    'Min2': 6,
    'Mod': 5,
    'Maj1': 4,
    'Maj2': 3,
    'Sev': 2,
    'Sal': 1
})

In [ ]:
data['FireplaceQu'] = data['FireplaceQu'].replace({
    'Ex': 5,
    'Gd': 4,
    'TA': 3,
    'Fa': 2,
    'Po': 1,
    'NA': 0
})

In [ ]:
data['FireplaceQu'].fillna(0, inplace=True)

In [ ]:
data['GarageType'] = data['GarageType'].replace({
    '2Types': 6,
    'BuiltIn': 5,
    'Attchd': 4,
    'Basment': 3,
    'Detchd': 2,
    'CarPort': 1,
    'NA': 0
})

In [ ]:
data['GarageType'].fillna(0, inplace=True)

In [ ]:
data['GarageYrBlt'].fillna(0, inplace=True)

In [ ]:
# GarageAgeCategory:  YrSold - GarageYrBlt.
data['GarageAge'] = data['YrSold'] - data['GarageYrBlt']
data['GarageAgeCategory'] = pd.cut(data['GarageAge'], bins=[-float('inf'), 0, 5, 10, 15, 20, float('inf')],
                                     labels=[6, 5, 4, 3, 2, 1])

In [ ]:
# change garage age category to integer

data['GarageAgeCategory'] = data['GarageAgeCategory'].astype(int)

In [ ]:
data['GarageFinish'] = data['GarageFinish'].replace({
    'Fin': 3,
    'RFn': 2,
    'Unf': 1,
    'NA': 0
})

In [ ]:
data['GarageFinish'].fillna(0, inplace=True)

In [ ]:
data['GarageQual'] = data['GarageQual'].replace({
    'Ex': 5,
    'Gd': 4,
    'TA': 3,
    'Fa': 2,
    'Po': 1,
    'NA': 0
})

In [ ]:
data['GarageQual'].fillna(0, inplace=True)

In [ ]:
data['GarageCond'] = data['GarageCond'].replace({
    'Ex': 5,
    'Gd': 4,
    'TA': 3,
    'Fa': 2,
    'Po': 1,
    'NA': 0
})

In [ ]:
data['GarageCond'].fillna(0, inplace=True)

In [ ]:
data['PavedDrive'] = data['PavedDrive'].replace({
    'Y': 3,
    'P': 2,
    'N': 1
})

In [ ]:
data['PoolQC'] = data['PoolQC'].replace({
    'Ex': 4,
    'Gd': 3,
    'TA': 2,
    'Fa': 1,
    'NA': 0
})

In [ ]:
data['PoolQC'].fillna(0, inplace=True)

In [ ]:
data['Fence'] = data['Fence'].replace({
    'GdPrv': 4,
    'MnPrv': 3,
    'GdWo': 2,
    'MnWw': 1,
    'NA': 0
})

In [ ]:
data['Fence'].fillna(0, inplace=True)

In [ ]:
data['MiscFeature'] = data['MiscFeature'].replace({
    'Elev': 5,
    'Gar2': 4,
    'Shed': 3,
    'TenC': 2,
    'Othr': 1,
    'NA': 0
})

In [ ]:
data['MiscFeature'].fillna(0, inplace=True)

In [ ]:
data['SaleType'] = data['SaleType'].replace({
    'New': 10,
    'WD': 9,
    'CWD': 8,
    'VWD': 7,
    'Con': 6,
    'ConLI': 5,
    'ConLw': 4,
    'ConLD': 3,
    'COD': 2,
    'Oth': 1
})

In [ ]:
data['SaleCondition'] = data['SaleCondition'].replace({
    'Normal': 6,
    'Family': 5,
    'AdjLand': 4,
    'Alloca': 3,
    'Partial': 2,
    'Abnorml': 1
})

In [ ]:
X = data.drop('SalePrice', axis=1)
y = data['SalePrice']

In [ ]:
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,building_age,RemodelAge,TotalBath,TotalPorch,TotalBsmtSFToGrLivAreaRatio,GarageAreaToLotAreaRatio,OverallQual_x_GrLivArea,building_age_category,LotFrontageToLotAreaRatio,Condition1_Artery,Condition1_Feedr,Condition1_Norm,Condition1_PosA,Condition1_PosN,Condition1_RRAe,Condition1_RRAn,Condition1_RRNe,Condition1_RRNn,Condition2_Artery,Condition2_Feedr,Condition2_Norm,Condition2_PosA,Condition2_PosN,Condition2_RRAe,Condition2_RRAn,Condition2_RRNn,KitchenAbvGr_x_KitchenQual,GarageAge,GarageAgeCategory
0,1,10,3,65.0,8450,2,0.0,1,3,4,1,3,5,5,7,5,2003,2003,3,2,10,10,4.0,196.0,4,3,6,4.0,3.0,0.0,6.0,1.0,856,4,5,2,4.0,856,854,0,1710,1,0,2,1,3,1,4,8,8,0,0.0,4.0,2003.0,2.0,2,548,3.0,3.0,3,0,61,0,0,0,0,0.0,0.0,0.0,0,2,2008,9,6,208500,5,5,4,61,0.500585,0.064852,11970,2,0.007692,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,4,5.0,5
1,2,5,3,80.0,9600,2,0.0,1,3,4,4,3,5,1,6,8,1976,1976,3,2,8,8,0.0,0.0,3,3,3,4.0,3.0,3.0,5.0,1.0,1262,4,5,2,4.0,1262,0,0,1262,0,1,2,0,3,1,3,6,8,1,3.0,4.0,1976.0,2.0,2,460,3.0,3.0,3,298,0,0,0,0,0,0.0,0.0,0.0,0,5,2007,9,6,181500,31,31,3,298,1.000000,0.047917,7572,2,0.008333,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,3,31.0,1
2,3,10,3,68.0,11250,2,0.0,2,3,4,1,3,5,5,7,5,2001,2002,3,2,10,10,4.0,162.0,4,3,6,4.0,3.0,1.0,6.0,1.0,920,4,5,2,4.0,920,866,0,1786,1,0,2,1,3,1,4,6,8,1,3.0,4.0,2001.0,2.0,2,608,3.0,3.0,3,0,42,0,0,0,0,0.0,0.0,0.0,0,9,2008,9,6,223500,7,6,4,42,0.515118,0.054044,12502,2,0.006044,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,4,7.0,4
3,4,11,3,60.0,9550,2,0.0,2,3,4,2,3,5,5,7,5,1915,1970,3,2,4,12,0.0,0.0,3,3,4,3.0,4.0,0.0,5.0,1.0,756,4,4,2,4.0,961,756,0,1717,1,0,1,0,3,1,4,7,8,1,4.0,2.0,1998.0,1.0,3,642,3.0,3.0,3,0,35,272,0,0,0,0.0,0.0,0.0,0,2,2006,9,1,140000,91,36,2,307,0.440303,0.067225,12019,1,0.006283,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,4,8.0,4
4,5,10,3,84.0,14260,2,0.0,2,3,4,4,3,5,5,8,5,2000,2000,3,2,10,10,4.0,350.0,4,3,6,4.0,3.0,2.0,6.0,1.0,1145,4,5,2,4.0,1145,1053,0,2198,1,0,2,1,4,1,4,9,8,1,3.0,4.0,2000.0,2.0,3,836,3.0,3.0,3,192,84,0,0,0,0,0.0,0.0,0.0,0,12,2008,9,6,250000,8,8,4,276,0.520928,0.058626,17584,2,0.005891,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,4,8.0,4

In [ ]:
data.select_dtypes(include=['object']).columns

Index([], dtype='object')

In [ ]:
data.isnull().sum().sort_values(ascending=False).head(20)

Id               0
MSSubClass       0
RemodelAge       0
building_age     0
SalePrice        0
SaleCondition    0
SaleType         0
YrSold           0
MoSold           0
MiscVal          0
MiscFeature      0
Fence            0
PoolQC           0
PoolArea         0
ScreenPorch      0
3SsnPorch        0
EnclosedPorch    0
OpenPorchSF      0
WoodDeckSF       0
PavedDrive       0
dtype: int64

## Data Modelling

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Linear Regression model
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

# Predictions and evaluation
y_pred_lr = lr_model.predict(X_test)
print("Linear Regression R^2 Score:", r2_score(y_test, y_pred_lr))
print("Linear Regression RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_lr)))

Linear Regression R^2 Score: 0.8584302888509472
Linear Regression RMSE: 32952.78236462729

In [ ]:
# Random Forest model
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Predictions and evaluation
y_pred_rf = rf_model.predict(X_test)
print("Random Forest R^2 Score:", r2_score(y_test, y_pred_rf))
print("Random Forest RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_rf)))

Random Forest R^2 Score: 0.8825132689634185
Random Forest RMSE: 30019.352958827007

In [ ]:
# XGBoost model
xgb_model = xgb.XGBRegressor(objective ='reg:squarederror', n_estimators=100, random_state=42)
xgb_model.fit(X_train, y_train)

# Predictions and evaluation
y_pred_xgb = xgb_model.predict(X_test)
print("XGBoost R^2 Score:", r2_score(y_test, y_pred_xgb))
print("XGBoost RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_xgb)))

XGBoost R^2 Score: 0.8862848841425344
XGBoost RMSE: 29533.57467891143

In [ ]:
def mean_absolute_percentage_error(y_true, y_pred):
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

# Calculate MAPE for each model
mape_lr = mean_absolute_percentage_error(y_test, y_pred_lr)
mape_rf = mean_absolute_percentage_error(y_test, y_pred_rf)
mape_xgb = mean_absolute_percentage_error(y_test, y_pred_xgb)

print("Linear Regression MAPE:", mape_lr)
print("Random Forest MAPE:", mape_rf)
print("XGBoost MAPE:", mape_xgb)

Linear Regression MAPE: 12.956843434636045
Random Forest MAPE: 10.61502311817514
XGBoost MAPE: 11.128621786808052

If the MAPE value is less than 10% then the regression model's ability is very good

If the MAPE value is between 10% - 20% then the regression ability of the model is good

If the MAPE value is in the range of 20% - 50% then the regression model's ability is feasible

If the MAPE value ranges more than 50% then the regression ability of the model is poor

The best Model is Random Forest Reggressor , otherwise Linear Regressions is the model with the lowest performance